name: Android CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Build with Gradle
      working-directory: ./src/fusion1-events
      run: gradle build

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: output
        path: ./src/fusion1-events/app/build/outputs/apk/**/*.apk

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      
      - name: Unit Test
        working-directory: ./src/fusion1-events
        run: gradle testDebugUnitTest

      - name: Upload Test Reports Folder
        uses: actions/upload-artifact@v3
        if: ${{ always() }} # IMPORTANT: Upload reports regardless of status
        with:
          name: output
          path: app/build/test-results # path to where the xml test results are stored

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Run Android Lint
      uses: yutailang0119/action-android-lint@v4.0.0
      with:
        report-path: build/reports/*.xml
        follow-symbolic-links: false
        ignore-warnings: false
